mqtt:
  host: mqtt
  user: <USUARIO_MQTT>
  password: <CONTRASEÑA_MQTT>

cameras:
  tio:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.209:8554/test
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
version: 0.14
